version: '3'
services:
  gpsutilapp:
    image: gpsapp
    container_name: gpsutilappcontainer
    ports:
      - "8081:8081"
  
  rewardapp:
    image: rewardsapp
    container_name: rewardappcontainer
    ports:
      - "8082:8082"

  tripapp:
    image: tripapp
    container_name: tripappcontainer
    ports:
      - "8083:8083"
    
  userapp:
    depends_on:
      - gpsutilapp
      - tripapp
      - rewardapp
    image: userapp
    container_name: userappcontainer
    ports:
      - "8080:8080"

